####
GET http://localhost:3000/todos/?status=TO%20DO

####

GET http://localhost:3000/todos/?priority=HIGH

####
PUT http://localhost:3000/todos/1/

Content-Type:application/json
{
    "status" : "DONE"
}

####
PUT http://localhost:3000/todos/4/

Content-Type: application/json

{
    "priority" :"HIGH"
}

####
PUT http://localhost:3000/todos/7/
Content-Type:application/json
{
    "todo" : "Some Task"
}

####
GET http://localhost:3000/todos/4/

####
DELETE http://localhost:3000/todos/10/

####
POST http://localhost:3000/todos/

Content-Type:application/json

{
  "id": 14,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}

####
GET http://localhost:3000/todos/?status=IN%20PROGRESS&priority=HIGH

####
GET http://localhost:3000/todos/?search_q=Play